AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template to connect DynamoDB Stream to EventBridge

Resources:
  EnrichLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        !Join [
          '',
          [
            !Ref 'AWS::AccountId',
            '-',
            !Ref 'AWS::Region',
            '-log-group-enrich-event-test',
          ],
        ]

  UserInfoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'deviceId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'deviceId'
          KeyType: 'HASH'
      BillingMode: 'PAY_PER_REQUEST'

  EnrichStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'states.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AppPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutLogEvents
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource:
                  - !GetAtt UserInfoTable.Arn

  EnrichStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: 'EXPRESS'
      Role: !GetAtt EnrichStepFunctionRole.Arn
      Name:
        !Join [
          '',
          [
            !Ref 'AWS::AccountId',
            '-',
            !Ref 'AWS::Region',
            '-enrich-event-test',
          ],
        ]
      DefinitionUri: enrichment-statemachine.asl.json
      DefinitionSubstitutions:
        userInfoTable: !Ref UserInfoTable
      Tracing:
        Enabled: true
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EnrichLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL

Outputs:
  StateMachineARN:
    Description: Arn of the state machine
    Value: !GetAtt EnrichStateMachine.Arn
